### ISSUE TITLE
No zlib in python 2.6

### ISSUE THREAD

**Issue by fulv** [gforcada/ansible-compile-python#2]
I ran this playbook on a bare Ubuntu 14.04.4.  Once complete, when I try to create a virtualenv with python2.6, I get:

```
root@wda:~# /srv/python2.6.9/bin/virtualenv foo
Traceback (most recent call last):
  File "/srv/python2.6.9/bin/virtualenv", line 2, in <module>
    import virtualenv
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 22, in <module>
    import zlib
ImportError: No module named zlib
```

In python 2.7 it works fine.

```
root@wda:~# /srv/python2.7.11/bin/python
Python 2.7.11 (default, Jun  6 2016, 20:24:44)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> zlib
<module 'zlib' from '/srv/python2.7.11/lib/python2.7/lib-dynload/zlib.so'>
```

However, in python 2.6 there is no `zlib.so` in `lib-dynload`.  I tried adding the switch `--with-zlib` to the `./configure` command, to no avail.

See also #1.

**Comment by fulv** [comment]
Hmm, I tried the changes in your branch `fix-zlib-on-py26`, but for 2.6 I get this error now:

```
root@test:~# /srv/python2.6.9/bin/virtualenv foo6
New python executable in /root/foo6/bin/python2.6
Also creating executable in /root/foo6/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /root/foo6/bin/python2.6 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/download.py", line 39, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 61, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/srv/python2.6.9/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/foo6/bin/python2.6 - setuptools pip wheel failed with error code 1
```

The good news is that 2.4 works now.

**Comment by gforcada** [comment]
@fulv yeah, I'm aware of that, I submitted https://github.com/pypa/virtualenv/issues/932 as I really have no idea what's the problem there... not even sure if it's virtualenv or pip to blame...

**Comment by gforcada** [comment]
That was fixed in https://github.com/gforcada/ansible-compile-python/commit/d77a49cf167766d253f4a9422f4c1ef53469b16e
